### ISSUE TITLE
Expect you to publish tus_client to pub.dev with a flutter example.

### ISSUE THREAD

**Issue by zxl777** [jjmutumi/tus_client#1]
Use pure dart to implement tus flutter client, which is very useful for flutter developers.

Expect you to publish tus_client to pub.dev with a flutter example.

Thank you.

**Comment by jjmutumi** [comment]
Good point! You can check here:

https://github.com/jjmutumi/tus_client/releases/tag/v0.0.1

https://pub.dev/packages/tus_client

Open to pull requests

**Comment by zxl777** [comment]
Thank you. Got it. I'm going to try.
