### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by Curvel** [jjmutumi/tus_client#15]
Are there any plans to migrate this package to null safety, in the near future?

**Comment by jjmutumi** [comment]
Yes. Probably by this weekend. PRs welcome though!

**Comment by jjmutumi** [comment]
Fixed in release [v1.0.0](https://github.com/jjmutumi/tus_client/releases/tag/v1.0.0)

**Comment by beevelop** [comment]
Nice, thank you @jjmutumi 🚀🍻
