### ISSUE TITLE
About custom chunk size while PATCH request

### ISSUE THREAD

**Issue by LAIMX** [jjmutumi/tus_client#16]
Hi, 

It is a useful resource that I can use it to upload larger size file...

I am using[ cloudflare stream service](https://api.cloudflare.com/#stream-videos-initiate-a-video-upload-using-tus) to upload my videos and store it.

cloudflare required minimum chunk size while uploading videos within PATCH request...
However, while I uploading video through cloudflare stream tus upload, it didn't meet the requirement from cloudflare, because `final fileChunk = await file.openRead(start, end).first` 
this snippet always return 65536 chunk size
 
Therefore, I need to custom the chunk size to meet cloudflare requirement(5242880 bytes)

hope someone can help me about this issues

**Comment by BboyKeen** [comment]
@LAIMX You can take a look at my PR
Using it fixes the issue for the upload with Cloudflare Stream

**Comment by BboyKeen** [comment]
Once new version has been published, you can close this issue @jjmutumi  ;)

**Comment by jjmutumi** [comment]
@LAIMX please upgrade to latest released [version `v1.0.1`](https://github.com/jjmutumi/tus_client/releases/tag/v1.0.1). Edit your `pubspec.yaml`:

```yaml
dependencies:
  tus_client: ^1.0.1
```
