### ISSUE TITLE
Is it working for AWS S3 Upload?

### ISSUE THREAD

**Issue by pratik-7span** [jjmutumi/tus_client#22]
Thanks for great plugin by tus.

Is this plugin is providing support for AWS S3 Upload?

**Comment by jjmutumi** [comment]
@pratik7span I believe AWS S3 doesn't support TUS directly but [tusd](https://github.com/tus/tusd) has can use S3 as a storage backend. Here is some more info: https://tus.io/blog/2016/03/07/tus-s3-backend.html
