### ISSUE TITLE
Very slow upload speeds

### ISSUE THREAD

**Issue by rodrigoschaefer** [jjmutumi/tus_client#23]
I recently changed the upload implementation in my app to use tus_client and upload speeds are almost 20x slower than the usual http POST, when using 2Mb chunks. I´ve managed to reach the previous level of speed by increasing the chunk size to 1Gb, but donest that defeat the purpose of using TUS?

Results with a 4.4Mb file upload:

Old HTTP post method: 6 seconds

TUS 10Mb chunk:  114 seconds
TUS 100Mb chunk:  17 seconds
TUS 1000Mb chunk: 7 seconds

`final xfile = XFile('$filePath');
    final client = TusClient(
      Uri.parse('https://$AppConfig.endpoint'),
        xfile,
      store: TusMemoryStore(),
        headers: {
        'Authorization': ' Bearer $token',
        'api-version': Constants.apiVersion,
        'uploadId':'$videoUploadId'
        },
      metadata: {
        'filename':'$fileName',
        'contentType':'multipart/form-data',
        'uploadId':'$videoUploadId'
      },maxChunkSize: 10 * 1024
    );

    try {
      await client.upload(
        onComplete: () {
          print('Complete!');
          // Prints the uploaded file URL
          print(client.uploadUrl.toString());
        },
        onProgress: (progress) {
          var p = progress.toInt();
          print('Progress: $progress , to int: $p');
          onSendProgress!(p);
        },
      );
    }catch(e){
      print((e as ProtocolException).message);
      return 500;
    }`

**Comment by dzab5** [comment]
did you fix this? or why did you close it?
