### ISSUE TITLE
work in background

### ISSUE THREAD

**Issue by khylenko** [jjmutumi/tus_client#27]
Now if you start uploading and minimize application OS can kill it and upload fails. Is it possible to make it work in background? Like in some torrent clients where you can minimize (and even swipe app from minimized) and it still downloads.

**Comment by jjmutumi** [comment]
That is out of the scope of this library. Though I have used a persistent [progress storage](https://github.com/jjmutumi/tus_client_file_store) and [background_fetch](https://pub.dev/packages/background_fetch) to get that kind of background uploading effect you are talking about.
