### ISSUE TITLE
Upload 300MB file - Exception has occurred.

### ISSUE THREAD

**Issue by zxl777** [jjmutumi/tus_client#3]
When upload 20%, the Exception has occurred.

```
  /// Get data from file to upload
  Future<Uint8List> _getData() async {
    final f = await file.open(mode: FileMode.read);

```
```
Exception has occurred.
FileSystemException (FileSystemException: Cannot open file, path = '/private/var/mobile/Containers/Data/Application/10AC6487-FAF4-44D8-9885-DD46040F3C08/tmp/com.example.example-Inbox/Every Second with You.mp3' (OS Error: No such file or directory, errno = 2))

```

**Comment by jjmutumi** [comment]
Can you confirm:

1 - The environment you are using library on (Android/iOS) version
2 - If the file was partially uploaded on the server
3 - If the issue is related to: https://github.com/flutter/flutter/issues/41046

**Comment by zxl777** [comment]
1.  iOS 13.6.1
2. Yes, the file was partially uploaded on the server.   I found 61MB data in the server ~/data folder.
3. I have upgraded the flutter to v1.20.3, and updated the new tus_client source today.

I guess the temporary file was deleted accidentally, please check the relevant code, thank you.
