### ISSUE TITLE
How to implement file uploading with tus in Flutter Web?

### ISSUE THREAD

**Issue by Maadhav** [jjmutumi/tus_client#6]
Could you please explain to me that how can I upload a file using this plugin in flutter web?

**Comment by jjmutumi** [comment]
Hello @Maadhav! Apologies but this plugin is not yet written to support flutter web. It's also not in my current plans to implement this. You could fork and make pull request?

**Comment by Maadhav** [comment]
Thanks for the reply @jjmutumi I tried implementing the same for wen using the dart:html package but there seems to be no straight forward way of doing binary operations with a file. Would try anyway. Also any idea you might have would help.

**Comment by jjmutumi** [comment]
I will see what I can come up with. Probably on the weekend.

**Comment by daniel-vera-g** [comment]
> I will see what I can come up with. Probably on the weekend.

Hey, would also be interested in flutter web support.
It would be awesome to see web support soon :+1:

**Comment by Maadhav** [comment]
@jjmutumi Thanks man, would really help me a lot.

**Comment by Maadhav** [comment]
@jjmutumi Any update on this?

**Comment by Maadhav** [comment]
I implemented tus client for flutter web without the pause functionality. Will be posting it in here soon.

**Comment by joe-getcouragenow** [comment]
@Maadhav Did you end up getting it working for Flutter Web
https://github.com/Maadhav/tus_client

I managed to get it working for Desktop

**Comment by Maadhav** [comment]
> @Maadhav Did you end up getting it working for Flutter Web
> https://github.com/Maadhav/tus_client
> 
> I managed to get it working for Desktop

It would run on any platform which supports dart:io, the issue with Flutter web that it needs dart:html to read or write the files. I have made significant changes in my local computer, sich the the uploading amd progress works.
The pausing not works, i don't why but I left that cause I didn't need that. Please let me know if you need my code in the repo you mentioned.

**Comment by joe-getcouragenow** [comment]
ok. we will fork and se if we can get it working. thanks

**Comment by jjmutumi** [comment]
@joe-getcouragenow check out the #9 pull request to see if it fulfills your requirements.

**Comment by joe-getcouragenow** [comment]
@jjmutumi thanks for letting me know !

I will try it out and feedback here...

**Comment by joe-getcouragenow** [comment]
@jjmutumi are you planning to also add a example that uses the web here: https://github.com/jjmutumi/tus_client/tree/master/example

**Comment by Maadhav** [comment]
@joe-getcouragenow Check out the example here: 
https://github.com/jjmutumi/tus_client/blob/adding-web-support/example

**Comment by joe-getcouragenow** [comment]
@Maadhav thanks. will try now !

**Comment by joe-getcouragenow** [comment]
Just tried the web branch and updated to use path based pubspec import for tus_client but i cant build.
Feels like i should wait a bit for Web example to do sorted out.

here is my make file anyway.

````

# https://github.com/jjmutumi/tus_client
# used by: https://github.com/jjmutumi/tus_client_file_store

# https://github.com/tus/tusd


SERVER_FSPATH=$(PWD)/tusd/cmd/tusd

FLU_CLIENT_FSPATH=$(PWD)/tus_client
FLU_FILE_STORE_EXAMPLE_FSPATH=$(PWD)/tus_client_file_store/example

print:

	@echo SERVER_FSPATH: $(SERVER_FSPATH)

	@echo FLU_CLIENT_FSPATH: $(FLU_CLIENT_FSPATH)
	@echo FLU_FILE_STORE_EXAMPLE_FSPATH: $(FLU_FILE_STORE_EXAMPLE_FSPATH)

dep:
	# go
	git clone https://github.com/tus/tusd

	# flu "adding-web-support" branch for now.
	git clone -b adding-web-support https://github.com/jjmutumi/tus_client

	git clone https://github.com/jjmutumi/tus_client_file_store
	
	
dep-delete:
	rm -rf ./tusd
	rm -rf ./tus_client
	rm -rf ./tus_client_file_store


### SERVER

server-run:
	cd $(SERVER_FSPATH) && go run main.go
	#http://0.0.0.0:1080/files/

### FLUTTER

flu-fix:
	# edit pubspec to use file based path to tus_client
	code ./tus_client_file_store/example/pubspec.yaml
	# tus_client:
    #    path: ../../tus_client
	code ./tus_client_file_store/pubspec.yaml
	# tus_client:
    #    path: ../tus_client

	# creates all the targets since they are not there in their code.
	cd $(FLU_FILE_STORE_EXAMPLE_FSPATH) && flutter create .

flu-mac:
	flutter config --enable-macos-desktop
	cd $(FLU_FILE_STORE_EXAMPLE_FSPATH) && flutter build macos

flu-web:
	cd $(FLU_FILE_STORE_EXAMPLE_FSPATH) && flutter run -d chrome

````

**Comment by jjmutumi** [comment]
@joe-getcouragenow the example has been updated in version **0.1.1**. You can check if it works for you?

**Comment by evanreichard** [comment]
@ jjmutumi It's working for me on web in 0.1.1

**Comment by joe-getcouragenow** [comment]
@evanreichard Ok i will try again !

**Comment by joe-getcouragenow** [comment]
@jjmutumi thanks !
